### ISSUE TITLE
List of non-standard modules needed

### ISSUE THREAD

**Issue by ckeeling** [JustinChu/JupiterPlot#13]
As you requested, I found I needed the following additional modules:
Config::General.pm
Math::VecStat
Set::IntSpan
List::MoreUtils

And those needed for CIRCOS as described here: [http://www.circos.ca/documentation/tutorials/configuration/perl_and_modules/](http://www.circos.ca/documentation/tutorials/configuration/perl_and_modules/)

**Comment by JustinChu** [comment]
Thanks! I've updated the readme!
