### ISSUE TITLE
Change labels and re-plot

### ISSUE THREAD

**Issue by gbdias** [JustinChu/JupiterPlot#18]
Hi,

- I would like to change my reference labels and regenerate the plot. Is it possible to run only the plotting step again after the analysis is completed?
- If so, should I just edit the prefix.seqOrder.txt file or something else?

Thanks

**Comment by JustinChu** [comment]
Hi sorry for the late reply,

You can rerun the pipeline from to the `prefix.karyotype` stage and edit the file and run the whole pipeline again:

```{bash}
jupiter name=prefix $OPTS prefix.karyotype
sed -i 's/chromosome/chr/g' prefix.karyotype
jupiter name=prefix $OPTS
```
In this example maybe the labels where `chromosome1` and I changed them to `chr1`. You can also just use a text editor if you want.

Is that what you meant?

**Comment by gbdias** [comment]
Yes, that does the trick. Thanks for the info!
