### ISSUE TITLE
Change color of the output and replot

### ISSUE THREAD

**Issue by scintilla9** [JustinChu/JupiterPlot#19]
Hi allI,

I am wondering if there's a simple way to change the color and replot the picture?
I try to modify the config file, however I noticed that in the end of the pipeline, the config file would be removed.
Is there any suggestions? Thanks!

**Comment by JustinChu** [comment]
The colours are determined in the karyotype stage so if you run the pipeline to that stage and edit the file you can set the colours yourself. In the [karyotype file](http://circos.ca/tutorials/lessons/ideograms/karyotypes/) change the colours and run the full pipeline.

```{bash}
jupiter name=prefix $OPTS prefix.karyotype
gedit prefix.karyotype #Manually change the files
jupiter name=prefix $OPTS
```

This is very similar to issue #18

**Comment by scintilla9** [comment]
Thanks for the explanation!
