### ISSUE TITLE
numbers of scaffold to render & their order

### ISSUE THREAD

**Issue by scintilla9** [JustinChu/JupiterPlot#20]
Hi all,

For the first question, I am curious about how to control the number of how many scaffold to be render, because I wish to plot all the scaffold in my assembly. 

My script looks like:

jupiter name=Test minBundleSize=5000 ng=100 m=500 ref=refercnece.fa fa=draft_genome.fa

However, when I mapped to different reference genome, the number of scaffolds are different.
For example, my genome has about 600 scaffolds, and they were all rendered when I mapped to reference genome A.

When I mapped to the reference genome B, only 350 scaffolds were rendered. The script I used were the same except the ref directory. What makes this difference?

For second question, I notice that some of the unmapped reads were insert between those that were mapped. Most of the unmapped scaffolds gather together on one side of the circle, but there were still some of unmapped reads spread among the mapped reads.

How can I control their order?

Thanks for your kindly reply.
Cheers

**Comment by JustinChu** [comment]
I might be misunderstanding you a bit but I'll try to explain how the script picks the number of scaffolds to render. The number of scaffold is a function of the contiguity and size of your assembly. When ng=100 is used only the largest scaffold summing to the reference size are used. If you want more you can set ng even higher (e.g. 120).

If seemingly unmapped scaffolds are included, between mapped scaffolds, that implies that they actually do map, but with such a small alignment portion the links are filtered out. You can get these links to render by decreasing the `minBundleSize` and possibly increasing the `maxGap`. If they are not mapped, I'm actually not sure how they ended up inserted between scaffolds, and this may indicate a bug in the code.

**Comment by scintilla9** [comment]
Thanks for the detailed explanation! I'll try that to see if it works.
