### ISSUE TITLE
Change path for Samtools

### ISSUE THREAD

**Issue by wlaw13** [JustinChu/JupiterPlot#22]
Is there a way to specify where Samtools is located? I'm using a server cluster and Samtools is installed in a common (unmovable) directory.

**Comment by JustinChu** [comment]
The makefile can be altered, but have you tried altering your `env` `PATH`.

E.g. 'export PATH=/path/to/sam/bin:$PATH`

**Comment by wlaw13** [comment]
That seems to have worked? I'm at least getting a new error:

Can't locate Config/General.pm in @INC (@INC contains: /software/centos7/usr/share/autoconf /software/centos7/usr/share/automake-1.13 /software/centos7/usr/lib64/perl5/vendor_perl /software/centos7/usr/share/perl5/vendor_perl /software/centos7/usr/lib64/perl5 /software/centos7/usr/share/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /work-zfs/amccall2/WDL/Nanopore_Test_Data/JupiterPlot/JupiterPlot/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks line 153.
BEGIN failed--compilation aborted at /work-zfs/amccall2/WDL/Nanopore_Test_Data/JupiterPlot/JupiterPlot/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks line 153.
make: *** [Testing.rv.links.bundled] Error 2
make: *** Deleting file `Testing.rv.links.bundled'

Any suggestions?

**Comment by JustinChu** [comment]
This is a missing perl module issue. Make sure you have all the modules needed as mentioned in the readme.
