### ISSUE TITLE
circos plotting error

### ISSUE THREAD

**Issue by mjmillerlab** [JustinChu/JupiterPlot#26]
Trying out this software. Really excited for a circos plot. However, it seems to fail in the drawing stage. This is the last bit of code (there is more of these "Use of..." above):

Use of uninitialized value $chromosomes{"ref61"} in concatenation (.) or string at /home/mmiller/JupiterPlot-master/bin/generateConf.pl line 388, <GEN7> line 4338.
 has no alignments
Use of uninitialized value $chromosomes{"ref63"} in concatenation (.) or string at /home/mmiller/JupiterPlot-master/bin/generateConf.pl line 388, <GEN7> line 4338.
 has no alignments
anna_chromW has no alignments
Use of uninitialized value $chromosomes{"ref65"} in concatenation (.) or string at /home/mmiller/JupiterPlot-master/bin/generateConf.pl line 388, <GEN7> line 4338.
 has no alignments
anna_chromZ_RaGOO has no alignments
cat test.rv.links | /home/mmiller/JupiterPlot-master/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks -max_gap 100000 -min_bundle_size 50000 > test.rv.links.bundled
num_links 112
num_initial_bundles 38
num_links_in_initial_bundles 112
num_passed_bundles 0 (0.00%)
num_links_in_passed_bundles 0 (0.00%)
#cat test.rv.links | perl /home/mmiller/JupiterPlot-master/bin/linkCollapse.pl -m 100000 -b 50000 > test.rv.links.bundled #simple bundle
cat test.fw.links | /home/mmiller/JupiterPlot-master/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks -max_gap 100000 -min_bundle_size 50000 > test.fw.links.bundled
num_links 1020
num_initial_bundles 147
num_links_in_initial_bundles 1020
num_passed_bundles 5 (3.40%)
num_links_in_passed_bundles 615 (60.29%)
#cat test.fw.links | perl /home/mmiller/JupiterPlot-master/bin/linkCollapse.pl -m 100000 -b 50000 > test.fw.links.bundled #simple bundle
awk ' { t = $5; $5 = $6; $6 = t; print; } ' test.fw.links.bundled > test.fw.links.bundled.flipped
cat test.rv.links.bundled test.fw.links.bundled.flipped > test.links.final
circos -noparanoid -conf test.conf
debuggroup summary 0.19s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
debuggroup summary 0.19s current working directory /home/mmiller/JupiterPlot-master
debuggroup summary 0.19s command /home/mmiller/miniconda3/bin/circos -noparanoid -conf test.conf
debuggroup summary 0.19s loading configuration from file test.conf
debuggroup summary 0.19s found conf file test.conf
debuggroup summary 0.35s debug will appear for these features: output,summary
debuggroup summary 0.35s bitmap output image ./test.png
debuggroup summary 0.35s SVG output image ./test.svg
debuggroup summary 0.35s parsing karyotype and organizing ideograms
Use of uninitialized value $start in substitution (s///) at /home/mmiller/miniconda3/bin/../lib/Circos/Karyotype.pm line 128, <F> line 2.
Use of uninitialized value $end in substitution (s///) at /home/mmiller/miniconda3/bin/../lib/Circos/Karyotype.pm line 129, <F> line 2.

  *** CIRCOS ERROR ***

      cwd: /home/mmiller/JupiterPlot-master

      command: /home/mmiller/miniconda3/bin/circos -noparanoid -conf test.conf

  Start [_undef_] and/or end [_undef_] coordinate in karyotype file don't appear
  to be numbers. Thousands separators , and _ are allowed, but not any other
  characters.

**Comment by JustinChu** [comment]
That is an odd error. Can you post the first few line of the following files:
test.fw.links.final
test.karyotype

Also what is the first error you see when the script for `test.conf`?

There could also be related to the naming convention of your input reference file or scaffolds or possibly extra newlines in those files that some scripts didn't account for in the code.

**Comment by drashwinelkar** [comment]
I think I reposted the same issue as a new one. You could check. I get the exact same error.
I am changing how my scaffolds are named to check if it resolves the problem.

**Comment by drashwinelkar** [comment]
I changed the way the sequences are named but the error still persists.

**Comment by JustinChu** [comment]
Likely fixed in #27
