### ISSUE TITLE
chromosome has no alignments!

### ISSUE THREAD

**Issue by drashwinelkar** [JustinChu/JupiterPlot#27]
I get this circos error when I run Jupiter. This error is to be found when I install circos via LinuxBrew or compile from source. So I guess it does not originate from circos itself.

circos -noparanoid -conf Ctet_ntJoin_k70_w1000.conf
debuggroup summary 0.10s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026001
debuggroup summary 0.10s current working directory /home/ashwin/Projects/tetanus/trimmed_raw_data/ntJoin
debuggroup summary 0.10s command /home/ashwin/sources/circos-0.69-9/bin/circos -noparanoid -conf Ctet_ntJoin_k70_w1000.conf
debuggroup summary 0.10s loading configuration from file Ctet_ntJoin_k70_w1000.conf
debuggroup summary 0.10s found conf file Ctet_ntJoin_k70_w1000.conf
debuggroup summary 0.17s debug will appear for these features: output,summary
debuggroup summary 0.17s bitmap output image ./Ctet_ntJoin_k70_w1000.png
debuggroup summary 0.17s SVG output image ./Ctet_ntJoin_k70_w1000.svg
debuggroup summary 0.17s parsing karyotype and organizing ideograms
Use of uninitialized value $start in substitution (s///) at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos/Karyotype.pm line 128, <F> line 2.
Use of uninitialized value $end in substitution (s///) at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos/Karyotype.pm line 129, <F> line 2.

  *** CIRCOS ERROR ***

      cwd: /home/ashwin/Projects/tetanus/trimmed_raw_data/ntJoin

      command: /home/ashwin/sources/circos-0.69-9/bin/circos -noparanoid -conf
      Ctet_ntJoin_k70_w1000.conf

  Start [_undef_] and/or end [_undef_] coordinate in karyotype file don't appear
  to be numbers. Thousands separators , and _ are allowed, but not any other
  characters.

 Stack trace:
 at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos/Error.pm line 425, <F> line 2.
	Circos::Error::fatal_error("data", "malformed_karyotype_coordinates", undef, undef) called at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos/Karyotype.pm line 131
	Circos::Karyotype::read_karyotype_file("Ctet_ntJoin_k70_w1000.karyotype", HASH(0x564897bd1bf8)) called at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos/Karyotype.pm line 92
	Circos::Karyotype::read_karyotype("file", "Ctet_ntJoin_k70_w1000.karyotype") called at /home/ashwin/sources/circos-0.69-9/bin/../lib/Circos.pm line 218
	Circos::run("Circos", "_cwd", "/home/ashwin/Projects/tetanus/trimmed_raw_data/ntJoin", "_argv", "-noparanoid -conf Ctet_ntJoin_k70_w1000.conf", "paranoid", 0, "configfile", ...) called at /home/ashwin/sources/circos-0.69-9/bin/circos line 536
/home/ashwin/sources/JupiterPlot/jupiter:97: recipe for target 'Ctet_ntJoin_k70_w1000.svg' failed
make: *** [Ctet_ntJoin_k70_w1000.svg] Error 255
make: *** Deleting file 'Ctet_ntJoin_k70_w1000.svg'
rm Ctet_ntJoin_k70_w1000.links.final Ctet_ntJoin_k70_w1000.rv.links.bundled Ctet_ntJoin_k70_w1000.conf Ctet_ntJoin_k70_w1000.fw.links.bundled Ctet_ntJoin_k70_w1000_scaffolds.fa.fai Ctet_ntJoin_k70_w1000.fw.links.bundled.flipped

Any idea why this is happening or how to sort this out?
Thanks!

**Comment by JustinChu** [comment]
Install the Config::General module and you should be able to finish the pipeline. There are many issues here though beyond this message however.

The first is that it is concerning that the issue looks like we are reading in an empty karyotype file. Can you post what your karyotype files look like? It could be filtering based on the `-m` parameter all the reference scaffolds out of the file. You can try setting `-m` to 0. With regards to the lack of alignments it may be worth checking the input files as the alignments are performed independently of filtering.

**Comment by drashwinelkar** [comment]
A snippet of the karyotype file :
chr - CP035787.1 CP035787.1 0 2807460 hue000

band CP035787.1 N N 0 83 black
band CP035787.1 N N 5893 6226 black
band CP035787.1 N N 6864 7070 black
band CP035787.1 N N 8007 8450 black
band CP035787.1 N N 8782 8796 black
band CP035787.1 N N 9147 9566 black

**Comment by drashwinelkar** [comment]
The input files are fasta genomes downloaded from ncbi

**Comment by JustinChu** [comment]
I've made some changes. Can you delete the current run and rerun the current branch.

**Comment by drashwinelkar** [comment]
Yes now it works. Thanks!
