### ISSUE TITLE
Set links between chromosomes

### ISSUE THREAD

**Issue by Karimi-81** [JustinChu/JupiterPlot#36]
Hi there,
I used the JupiterPlot to present the synteny between two genomes using default parameters:
./jupiter name=genome_two ref="polished_assembly.fa" fa="C_1.0_genomic.fna" t=32 ng=75

Attached is the circos  plot generated. I wonder how can I change the color and thickness of links (I want wider links) between chromosomes. In addition, how it is possible to add the names of scaffolds (or chromosomes) to second genome (right hand side of image). 
Regards
![circos_2](https://user-images.githubusercontent.com/79817636/119244652-112b7700-bb49-11eb-9ad2-9d7dfddf562b.png)

**Comment by JustinChu** [comment]
Sorry if this reply is too late. To create wider links you could try to change the parameters `minBundleSize` (decrease) and `maxGap` (increase) which will allow larger gaps when between aligned regions. Any additional changes will require development probably tweaking filtering and mapping parameters.

**Comment by JustinChu** [comment]
Stale issue. Closing.
