### ISSUE TITLE
No links despite large regions of similarity visible in dot plot from MUMMER alignment

### ISSUE THREAD

**Issue by mptrsen** [JustinChu/JupiterPlot#38]
There seems to be an incongruence between JupiterPlot and a "regular" dot plot from a MUMMER (nucmer) alignment of two genomes of a chlorophyte algae species (21 Mbp). JupiterPlot shows no connections, whereas the dot plot shows large regions of similarity pretty much throughout the entire genome.

![JupiterPlot](https://user-images.githubusercontent.com/509369/192989733-619a69db-f32c-4e53-bba6-5c5b42861852.png)

![MUMMER alignment](https://user-images.githubusercontent.com/509369/192990489-222a64f9-ec5f-44e1-b490-0c396befb3c3.png)

Please find the genomes and results here: https://uni-bonn.sciebo.de/s/LrubQxY319Lf8nn

I ran both JupiterPlot and MUMMER with default parameters:

```
cd jupiterplot
jupiter name=Micpus ref=../data/Micpus1545_MpusillaCCMP1545_228_v3.0.fasta fa=../data/MicpusNOUM17_MicpuN3v2_AssemblyScaffolds.fasta
```

```
cd mummer_dotplot
nucmer --coords ../data/Micpus1545_MpusillaCCMP1545_228_v3.0.fasta ../data/MicpusNOUM17_MicpuN3v2_AssemblyScaffolds.fasta
```

To visualise the MUMMER alignment, I used Dot (https://dot.sandbox.bio/). It requires input reformatted by the `DotPrep.py` script included in the mummer_dotplot directory. It was run as:

```
python DotPrep.py --delta out.delta --out Micpus
```

This produces the files Micpus.coords and Micpus.coords.idx that are also in the [uploaded results](https://uni-bonn.sciebo.de/s/LrubQxY319Lf8nn
), and can be used in the [Dot viewer](https://dot.sandbox.bio) to reproduce the dot plot above.

I tried setting `minBundleSize=1` and `maxGap=9999999999` with the effect that it renders three small connections:

![JupiterPlot, minBundleSize=1 maxGap=9999999999](https://user-images.githubusercontent.com/509369/192996511-0f76159c-00a3-435d-95c4-43ac84ccd21c.png)

Do I need to set other parameters? Or how can I make JupiterPlot's output show the obvious similarity between the two genomes that is visible in the dot plot?

**Comment by JustinChu** [comment]
I think the key would be to look at the minimap2 alignments. To fix this issue I think I would need to see the resulting bed file created in the pipeline. There could also be an element of filtering involved: https://github.com/JustinChu/JupiterPlot/blob/45676f3ee3b2f2134941cf6276a51e3bdaa07e0b/jupiter#L80
If the genome is highly repetitive it is possible that I have been filtering out links.

**Comment by JustinChu** [comment]
If it is filtering related it seems I should probably include an option to allow repetitive links or change the default behaviour to not filter on mapping quality at all.

**Comment by JustinChu** [comment]
@mptrsen Can you try the latest commit with the MAPQ parameter set to 0?

**Comment by sven1990** [comment]
Hi @JustinChu,
for my dataset I have checked the bed file and all the alignments I am missing in the plot are there but are missing in the links, karyotype, and SeqOrder files. Filtering by mapping Q seems not to be the issue. 
I could also send you my two assemblies if that helps. The genomes are standard mammal genomes and very conserved between the two species so I would assume this is not an issue of repeats.

<img width="819" alt="Bildschirmfoto 2022-11-04 um 11 44 45" src="https://user-images.githubusercontent.com/36346531/199956673-ae421f05-b722-4a14-8bef-07432ef29777.png">

**Comment by mptrsen** [comment]
> @mptrsen Can you try the latest commit with the MAPQ parameter set to 0?

Same result, sorry. I'll upload the alignment SAM next week.

**Comment by JustinChu** [comment]
@sven1990 Sending me the assemblies would be very helpful. Also, let me know what syntenic regionyou expect to see on the plot that is only visible when you subset the chromosome.

**Comment by sven1990** [comment]
Hi @JustinChu, 

thanks for looking into it. 

You can download the assemblies from my dropbox 
[(https://www.dropbox.com/sh/rvp92mdi9pcsw4h/AAAi3HpFwvykg7HwwUp4pP2da?dl=0)]

I expect to see syntenic regions between the largest 19 scaffolds (chromosomes) of both assemblies. However, the plot so far does not show synteny between scaffold_19 of VMU_Ajub_asm_1.0 and scaffold NC_057357.1 from GCF_016509475.1. 

As I mentioned before, there are alignments in the bed file, but in the end, they are missing in the plot.

Thanks again!

Sven

**Comment by mptrsen** [comment]
I have updated the [uploaded data](https://uni-bonn.sciebo.de/s/LrubQxY319Lf8nn) with the recent SAM. Hope that helps.

(samtools flagstats reports a 100% mapping rate)

I ran Jupiter with:

```
jupiter name=Micpus ref=reference.fa fa=scaffolds.fa MAPQ=0
```

(samtools flagstats reports a 100% mapping rate)

**Comment by sven1990** [comment]
Hi @JustinChu, 

I know you are likely busy with other tasks but did you maybe have the chance to look into my two assemblies?

I very much appreciate your help.

**Comment by JustinChu** [comment]
@sven1990 I'll try to have a fix or explanation by Friday.

**Comment by JustinChu** [comment]
@mptrsen I think there might be a conflict of temporary files causing issues in your output. I get different results when I run the data with the same parameters `minBundleSize=1` and `maxGap=9999999999` :
![Micpus_1_9999999999](https://user-images.githubusercontent.com/1156466/204107793-6aaff806-9a70-4e9a-8aef-078416fb434a.svg)

Having such a high max gap probably isn't very accurate to true synteny interpretation so here are my results with `minBundleSize=1` and `maxGap=100000` (default):
![Micpus_1_100000](https://user-images.githubusercontent.com/1156466/204107804-1e83cf92-ecf1-4712-a8fd-8dbe49686679.svg)

I also ran it off your sam file and got the same figure so I suspect it is an issue with the `*links*` files.

The file conflict is something I think I can resolve the issue by making relevant parameters part of the temporary filenames so this happens less, though at the moment make sure you are removing and `*links*` file after changing parameters.

**Comment by JustinChu** [comment]
@sven1990 The issue in your case was the `ng` parameter was filtering the scaffolds that you were interested in. I honestly should have recognized it sooner. Sorry, I took so long. Here are the results with `ng=120`:
![test](https://user-images.githubusercontent.com/1156466/204108053-561d35e8-cbd9-4019-b6d8-910b1718fbc9.svg)

Perhaps I should change the default as assemblies are becoming far more contiguous these days. Maybe a more useful filtering parameter rather than `ng` would be a minimum size like the parameter I use for the reference genome.

**Comment by sven1990** [comment]
@JustinChu thank you a lot, really appreciate your help. I did not know you could set ng >100.
