### ISSUE TITLE
Can I retain some config files removed by your script?

### ISSUE THREAD

**Issue by nzx9581** [JustinChu/JupiterPlot#41]
Hi Developer,
I am wondering how can I keep configure files that are removed at the last step of your script, which shows the information like that:
`rm test.rv.links.bundled test.fw.links.bundled test.conf test.fw.links.bundled.flipped`
I checked jupiter script, however, I found that you didn't use `rm` command in bash to delete these files. So I guess you remove these files in your perl scripts, but I don't know which one is the right one that I should modify. Can you tell me how to do that? Thanks in advance.

**Comment by JustinChu** [comment]
Sorry for the late reply but the files are removed by make, if you want to retain them you can run the makefile and just specify the filenames to retain.

**Comment by JustinChu** [comment]
For example `jupiter ng=75 name=dm ref="dros.fa" fa="drosScaf.fa" dm.rv.links.bundled dm.fw.links.bundled test.conf dm.fw.links.bundled.flipped` should retain the files.
