### ISSUE TITLE
Request: Option to always show all contigs

### ISSUE THREAD

**Issue by alexweisberg** [JustinChu/JupiterPlot#42]
Thanks for writing this tool, it works very well. I was wondering if it would be possible to add an option such that all contigs (query and ref) are shown, even if they don't map. I know the ng option can be increased, but this can be kind of fiddly to find the right value. It would be nice if there were a flag to set that automatically just shows everything, even if it would be clunky looking. Thanks!

**Comment by JustinChu** [comment]
I've added that if you set `ng=0` , I wouldn't recommend for assemblies with small fragments but the option is now there if someone wants it.
