### ISSUE TITLE
Effect of mapping parameters

### ISSUE THREAD

**Issue by tanpham15** [JustinChu/JupiterPlot#43]
Dear Justin Chu and authors,

When I changed the parameters of minimap2 (from asm10 -> asm20) it helped to increase the connection, and it looks similar to result from nucmer dot plot.
![nucmer_dotplot](https://github.com/JustinChu/JupiterPlot/assets/112657042/2cf4c453-a555-4ace-b00c-0e6c600885dd)

However, there is only a weird connection, but it make the figure become nonsense. Please take a look these figures
bellow are results from minimap2 with asm10 and asm20
![plot_ver4_asm10](https://github.com/JustinChu/JupiterPlot/assets/112657042/9e8f7e47-d249-46cc-8d83-9af738e8bb54)
![jupiterplot_asm20](https://github.com/JustinChu/JupiterPlot/assets/112657042/ee96a82a-4745-4b00-972a-953a0d7acb11)

Could you please let me know how can I fix it?
P/S: I used `minBundleSize=1` and `maxGap=9999999999` from the previous issues https://github.com/JustinChu/JupiterPlot/issues/38

**Comment by JustinChu** [comment]
I'm not entirely sure what kind of output you are expecting for the plot. Is it that you expected to see more connections?

In this case, I would not increase maxGap too much. It basically merges together links but it also gives fairly strange results for example CHR31 to the bottom contig.

Maybe lowering the `MAPQ` threshold could help to recover mapped sequencing as they are filters.

For your purposes, it may actually be beneficial to actually run the pipeline with the reference and contigs in reverse. If not to see what it looks like.

**Comment by JustinChu** [comment]
Stale
