### ISSUE TITLE
Problems with the aesthetics of the plot 

### ISSUE THREAD

**Issue by jacolmen** [JustinChu/JupiterPlot#44]
Dear Justin, 

Thanks for this amazing, super useful and straightforward tool. 

I ran an analysis on two mammal genomes (both are 24 almost identical chromosomes) using the following parameters: 

./jupiter name=PTru_pMa ref=../prunned_genomes/pMa.fasta fa=../prunned_genomes/pTru.fasta t=20 m=1000000 ng=99 labels=both i=24

Here I attach the png output, which I consider is a little bit weird in terms of the colors of the polygons representing the chromosomes of my reference. Do you know the reason I'm getting those colors? I know that one can set the colors manually in the karyotype file but when I see analyses from other users (as well as the example in your github) colors are different even when running default parameters. I would appreciate if you can tell me if I'm making some mistakes.

Have a good week, 

Javier C. 
![PTru_pMa](https://github.com/JustinChu/JupiterPlot/assets/110560038/4318a909-a7c0-4d8d-a5b2-39bdebf32c33)

**Comment by JustinChu** [comment]
The PNG does not handle transparency (a circos issue) well. The colours are slightly transparent. Try to open the SVG that is also produced. The program will have to render it and thus is non consistant but something like gimp should do something reasonable.
