### ISSUE TITLE
CIRCOS ERROR cmd: circos -noparanoid -conf test.conf

### ISSUE THREAD

**Issue by ykkim0127** [JustinChu/JupiterPlot#45]
I got this circos error when I run Jupiter using own test data using Ecoli. 
All perl modules are downloaded and I am stuck in this step..
How can I solve this ? I editted pathway information, because it looks messy to read.

--
bash 1_jupiter_script.sh 
grep -v XA test-agp.sam | grep -v '^@' | awk '{if($5 > 50 || $5 == "" ) print}' | perl JupiterPlot-1.0/bin/samToBed.pl > test-agp.bed
samtools faidx test_scaffolds.fa
perl JupiterPlot-1.0/bin/generateConf.pl -n 75 -r JupiterPlot-1.0/config/rawConf.conf -p test -s test_scaffolds.fa.fai -b test-agp.bed -a test.agp -k test_reference.karyotype
sed: -e expression #1, char 18: unknown option to `s'
sed: -e expression #1, char 14: unknown option to `s'
Generating Karyotype file
Selecting 2 scaffolds to render
Generating Links file
chromosomes_order = scaf1,ref0
cat test.rv.links | JupiterPlot-1.0/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks -max_gap 100000 -min_bundle_size 10000 > test.rv.links.bundled
num_links 27
num_initial_bundles 15
num_links_in_initial_bundles 27
num_passed_bundles 0 (0.00%)
num_links_in_passed_bundles 0 (0.00%)
cat test.fw.links | JupiterPlot-1.0/circos-tools-0.22/tools/bundlelinks/bin/bundlelinks -max_gap 100000 -min_bundle_size 10000 > test.fw.links.bundled
num_links 265
num_initial_bundles 9
num_links_in_initial_bundles 265
num_passed_bundles 1 (11.11%)
num_links_in_passed_bundles 247 (93.21%)
awk ' { t = $5; $5 = $6; $6 = t; print; } 'test.fw.links.bundled > test.fw.links.bundled.flipped
cat test.rv.links.bundled test.fw.links.bundled.flipped > test.links.final
perl JupiterPlot-1.0/circos-0.69-3/bin/circos -noparanoid -conf test.conf
debuggroup summary 0.16s welcome to circos v0.69-3 24 Jun 2016 on Perl 5.026001
debuggroup summary 0.16s current working directory circos-test
debuggroup summary 0.16s command JupiterPlot-1.0/circos-0.69-3/bin/circos -noparanoid -conf test.conf
debuggroup summary 0.16s loading configuration from file test.conf
debuggroup summary 0.16s found conf file test.conf
debuggroup summary 0.28s debug will appear for these features: output,summary

  *** CIRCOS ERROR ***

      cwd: circos-test

      command: JupiterPlot-1.0/circos-0.69-3/bin/circos
      -noparanoid -conf test.conf

  Cannot find the directory [./circos-test] for
  writing image files.

  If you are having trouble debugging this error, first read the best practices
  tutorial for helpful tips that address many common problems

      http://www.circos.ca/documentation/tutorials/reference/best_practices

  The debugging facility is helpful to figure out what's happening under the
  hood

      http://www.circos.ca/documentation/tutorials/configuration/debugging

  If you're still stumped, get support in the Circos Google Group. Please
  include this error and all your configuration and data files.

      http://groups.google.com/group/circos-data-visualization

  Stack trace:
 at JupiterPlot-1.0/circos-0.69-3/bin/../lib/Circos/Error.pm line 423.
	Circos::Error::fatal_error("io", "no_directory", ".circos-test", "image files") called at circos-0.69-3/bin/../lib/Circos.pm line 167
	Circos::run("Circos", "_argv", "-noparanoid -conf circos-test"..., "paranoid", 0, "_cwd", "circos-test", "configfile", ...) called at JupiterPlot-1.0/circos-0.69-3/bin/circos line 529
JupiterPlot-1.0/jupiter:100: recipe for target 'circos-test/test.svg' failed
make: *** [circos-test/test.svg] Error 255
rm test.links.final circos-test/test.rv.links.bundled test-agp.bed est.conf test.fw.links.bundled test_scaffolds.fa.fai test.fw.links.bundled.flipped

--

And as a result of running Jupiter, I got those outputs.
Apr  4 02:30 1_jupiter_script.sh
4.0K Apr  4 02:22 Ecoli-K12
drw4.0K Apr  4 02:23 Ecoli-O157
 188 Apr  4 02:30 test.agp
5.4M Apr  4 02:30 test-agp.fa
16M Apr  4 02:30 test-agp.sam
16K Apr  4 11:40 test.fw.links
69 Apr  4 11:40 test.karyotype
124 Apr  4 02:30 test_reference.fa -> GCF_000005845.2_ASM584v2_genomic.fna
12 Apr  4 02:30 test_reference.fa.amb
39 Apr  4 02:30 test_reference.fa.ann
1.2M Apr  4 02:30 test_reference.fa.pac
2.3M Apr  4 02:30 test_reference.fa.sa
33 Apr  4 02:30 test_reference.karyotype
1.6K Apr  4 11:40 test.rv.links
125 Apr  4 02:30 test_scaffolds.fa -> GCF_000008865.2_ASM886v2_genomic.fna
30 Apr  4 11:40 test.seqOrder.txt

**Comment by JustinChu** [comment]
What is in your `1_jupiter_script.sh` ? Also what OS are you running?

**Comment by JustinChu** [comment]
There does appear to be be something odd happening in the `sed` command in one of the scripts. Can you also run `sed --version` in your console?

**Comment by ykkim0127** [comment]
Hi. Thanks for promt reply.

Ths script is as below,

`jupiter name=./circos-test/test ref=GCF_000005845.2_ASM584v2_genomic.fna fa=GCF_000008865.2_ASM886v2_genomic.fna t=96`

And when I run sed --version, it prints

```
sed (GNU sed) 4.4
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```

**Comment by JustinChu** [comment]
Hmm I think the syntax issues originate using a name that I did expect. Try to run it with a name without any /.

**Comment by ykkim0127** [comment]
Without path information, error is fixed ! Thanks for quick help.
