### ISSUE TITLE
can this pipeline be added to a container?

### ISSUE THREAD

**Issue by KristinaGagalova** [JustinChu/JupiterPlot#46]
Hi @JustinChu , 

Can this be added to the conda or any other container system?

Thanks

**Comment by JustinChu** [comment]
Hopefully it should be seamless since Circos is conda but I actually had some issues with getting Circos installed with conda that I hope wasn't a common issue.

**Comment by KristinaGagalova** [comment]
That would be great. Thank you 
In case you have issues with that, would it be possible to add it to docker ?

**Comment by JustinChu** [comment]
Has been added to conda: https://github.com/bioconda/bioconda-recipes/pull/49318#event-13547846254
