### ISSUE TITLE
Synteny graph not representing alignment results: I appreciate your help

### ISSUE THREAD

**Issue by BioJules** [JustinChu/JupiterPlot#48]
HI Justin, 

First of all, thanks a lot for your Pipeline. It helped me a lot for showing my preliminary results. Here I aligned my repeat-masked genome assembly to a reference genome (95% of the reference genome is covered) with minimap2 and got a really nice graph.
However, I encounter a problem with my final results. I aligned my non repeat masked genome assembly to another genome. I did the same as for the preliminary results. The alignment reveals that 94% of the reference genome are covered by my scaffolds. The synteny plot that was created by the pipeline does not show this (see below). I have tried different settings but the pipeline shows only a few of my scaffolds and almost nothing changed with the different settings. 

1.  `jupiter name=NSCvsHLE_T4 ref=NSC_Genome_16Chr_XY_unwrapped.fasta fa=HLE_GenomeAssembly_241scaffolds_unwrapped.fa sam=HLEvsNSC_nonMaskedT4.sam t=18 labels=both maxGap=15000`

2.  `jupiter name=HLEvsNSC_T5 ref=NSC_Genome_16Chr_XY_unwrapped.fasta fa=HLE_GenomeAssembly_241scaffolds_unwrapped.fa sam=HLEvsNSC_nonMaskedT4.sam t=18 labels=both maxGap=150000`

3.  `jupiter name=HLEvsNSC_T6 ref=NSC_Genome_16Chr_XY_unwrapped.fasta fa=HLE_GenomeAssembly_241scaffolds_unwrapped.fa sam=HLEvsNSC_nonMaskedT4.sam t=18 m=50000 maxScaff=60 i=360 g=150000 gScaff=150000 labels=both maxGap=150000 minBundleSize=5000 MAPQ=0`

I would appreciate it if you could help me getting a graph that represents the results. I don't understand why some of the reference chromosomes are not covered. Thanks a lot
Best wishes 
Julia

![NSCvsHLE_T4](https://github.com/user-attachments/assets/6f92b7f4-eff3-4b34-91a3-c1bca625209d)

**Comment by JustinChu** [comment]
The pipeline filters smaller contigs. Try setting `ng=100` or even higher.

**Comment by BioJules** [comment]
Thanks a lot, now I figured out how to show the number of scaffolds. However, I encountered another issue. In the file below, the single lines (links) that are crisscrossing are irritating. These are probably repeats. How can I get rid of them so that I can see the main links better. 
Thank you a lot. 
![MANvsHLE_T5](https://github.com/user-attachments/assets/5fd88097-986f-433c-98f0-e9ed28577ffe)

**Comment by JustinChu** [comment]
What is the `MAPQ` setting? Increasing the `MAPQ` threshold can help with that if they are indeed repeats though it maybe noted that depending on how repetitive the genome is there could be collateral damage in a sense on other links as well.

If this doesn't work there is a good chance these might not be repeats. However if they are small enough you could filter using ` minBundleSize` though this is purely a length based threshold so it can remove real links you may be interested in.

**Comment by BioJules** [comment]
Thank you for your fast reply. I tried different parameter combinations and nothing changed in the graph.
The max mapping quality is 60 and my general filter was MAPQ=50. 

Here are commands
1) `jupiter name=MANvsHLE_T5 ref=GenomeAssembly_unwrapped.fa sam=Test.sam t=40 labels=both maxGap=20000 maxScaff=36 MAPQ=50 ng=99 m=5000000 `

2) `jupiter name=MANvsHLE_T5 ref=GenomeAssembly_unwrapped.fa sam=Test.sam t=40 labels=both maxGap=20000 maxScaff=36 MAPQ=50 ng=99 m=5000000 minBundleSize=3000000`

3) `jupiter name=MANvsHLE_T5 ref=GenomeAssembly_unwrapped.fa sam=Test.sam t=40 labels=both maxGap=20000 maxScaff=36 MAPQ=50 ng=99 m=5000000 minBundleSize=10000000`

The graphs look all the same (as the one in my last post). It seems that the parameter minBundleSize has no effect at al.

What am I doing wrong?
Thanks again
Julia

**Comment by JustinChu** [comment]
Hmm, how large do you think those repeats? Depends what the size you might need to use a really large `minBundleSize`. Or maybe there is a bug.

**Comment by JustinChu** [comment]
Do you see any change at all changing the values? For perspective if that genome is human sized I'd say the contiguous chunks could be megabases in size so I'd keep going larger until you notice entire large syntenic regions you want to keep disappearing.

**Comment by BioJules** [comment]
I will run it with a low number of minBundleSize. However, as the m is set to 5mio (only use genomic reference chromosomes larger than this value) I thought that setting minBundleSize to a similar or even bigger amount would only show ribbons that are at least as wide as the smallest reference ideogram.

I will keep you updated

**Comment by BioJules** [comment]
The result with the minBundleSize=10 is identical to the ones with high minBundleSize. Is it a bug?
BTW the lines 13 and 15 of my log file are commented out. Both commands are related to linkCollaps. Is this important?

**Comment by JustinChu** [comment]
Oh, linkCollapse.pl that was some code I was experimenting on a long time ago. I actually forgot I left it in there (probably should be removed). However, it shouldn't be an issue.

Sanity check with `maxGap=1` and `minBundleSize=1`. You can also set minBundleSize to larger than your largest contig? It should then not render anything at all.

Identical plots in general are a bit concerning. I don't think your log reflects this but are re-running the pipeline in the same location?  If you are you should remove these files otherwise it will use old files and render the same plot multiple times:
```
prefix.seqOrder.txt
prefix.svg
prefix.links
prefix.karyotype
prefix.conf
```
The pipeline design was to allow me to prototype while not having to re-rerun alignment stage of the pipeline but it can lead to issues. I think I might try to make some changes to the code that automatically detects parameter changes to the runs and to re-run specific the pipeline perhaps so this doesn't happen.

**Comment by JustinChu** [comment]
On a drosphilia dataset:

![test](https://github.com/user-attachments/assets/40f51dd3-46a9-400a-81df-b591a061d86d)
If running `maxGap=1` and `minBundleSize=1`

![test](https://github.com/user-attachments/assets/3e8a6532-0938-4578-aa9b-338170ddf135)
If running `minBundleSize=100000000000`

**Comment by BioJules** [comment]
Hi Justin, 

I have no idea what happened but I just reinstalled the Jupiter Pipeline with conda and now the parameters have an effect again. The first time I have installed it from source (git clone https://github.com/JustinChu/JupiterPlot.git). So maybe there is a bug in the source file. 

I appreciate your help. 
Have a wonderful day.
Julia

**Comment by JustinChu** [comment]
Hmm if the issue was getting the same plot I suspect it had to with it accidentally using older files in the same directory but I can't say for certain and I might update the code to compensate for this in the future.

Anyway, I'm happy it worked for you.
