### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by natsyam** [JustinChu/JupiterPlot#49]
Hello! Thank you for this tool!
`labels = ref        #Shows reference chromosome name "ref", scaffolds "scaf" or "both"`
I think you have a small typo in the tutorial, if you use it this way, you get the error `make: *** empty variable name.  Stop.`
I tried the variant without spaces  `labels=ref` and everything worked.
Maybe this will help someone.

**Comment by JustinChu** [comment]
fixed 8874c2b02d908b5de95db9f0258cdf36d75f871b
